# Generated by Django 3.0.5 on 2021-04-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20191023_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
